name: ci

on: [push, pull_request]

jobs:
  stable:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-13
          - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4

      - name: install
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: install on windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: moon version
        run: |
          moon version --all

      - name: moon install
        run: |
          moon update
          moon install

      - name: moon info
        run: |
          moon info --target native
          git diff --exit-code

      - name: moon check
        run: moon check --deny-warn --target native

      - name: format check
        run: |
          moon fmt --check

      - name: Run moon test
        run: |
          moon test --target native

      - name: moon test --doc
        run: |
          moon test --doc --target native

      - name: moon build
        run: |
          moon build --target native

  bleeding:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-13
          - windows-latest
    continue-on-error: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: install
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s bleeding
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: install on windows
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          MOONBIT_INSTALL_VERSION: bleeding
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: moon version
        run: |
          moon version --all

      - name: moon install
        run: |
          moon update
          moon install

      - name: moon info
        run: |
          moon info --target native
          git diff --exit-code

      - name: moon check
        run: moon check --deny-warn --target native

      - name: format check
        run: |
          moon fmt --check

      - name: Run moon test
        run: |
          moon test --target native

      - name: moon test --doc
        run: |
          moon test --doc --target native

      - name: moon build
        run: |
          moon build --target native
